# Generated by Django 3.2.15 on 2024-03-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registries_name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='仓库名称')),
                ('registries_url', models.URLField(max_length=100, unique=True, verbose_name='仓库地址')),
                ('registries_auth', models.BooleanField(default=False, verbose_name='认证状态')),
                ('registries_username', models.CharField(blank=True, max_length=100, verbose_name='仓库用户')),
                ('registries_password', models.CharField(blank=True, max_length=200, verbose_name='仓库密码')),
                ('encryption_key', models.CharField(blank=True, max_length=255, verbose_name='加密密钥')),
                ('registries_remarks', models.TextField(blank=True, verbose_name='备注')),
                ('registries_createdat', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '镜像仓库',
                'verbose_name_plural': '镜像仓库',
            },
        ),
    ]
