# Generated by Django 4.2 on 2024-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_registries'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=30, null=True, verbose_name='资产名称')),
                ('host_address', models.CharField(max_length=30, null=True, verbose_name='主机IP地址')),
                ('host_port', models.CharField(max_length=6, null=True, verbose_name='端口')),
                ('host_username', models.CharField(max_length=30, null=True, verbose_name='用户名')),
                ('host_password', models.CharField(max_length=30, null=True, verbose_name='密码')),
                ('host_status', models.CharField(max_length=30, null=True, verbose_name='主机存活状态')),
                ('host_createdat_time', models.DateTimeField(auto_now=True, null=True, verbose_name='数据上报时间')),
            ],
            options={
                'verbose_name': '主机列表',
                'verbose_name_plural': '主机列表',
            },
        ),
    ]
