# Generated by Django 4.2 on 2024-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_hostmonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmonitoring',
            name='host_encryption_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='加密密钥'),
        ),
    ]
