name: build udocker release

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write

env:
  PYTHON_VERSION: '3.9.13'
  DOCKER_IMAGE_NAME: 'udocker'
  DOCKER_NAMESPACE: 'llody'
  DOCKER_REGISTRY_HUAWEI: 'swr.cn-southwest-2.myhuaweicloud.com'
  DOCKER_REGISTRY_ALIYUM: 'registry.cn-hangzhou.aliyuncs.com'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  HWYUM_DOCKER_USERNAME: ${{ secrets.HWYUM_DOCKER_USERNAME }}
  HWYUM_DOCKER_PASSWORD: ${{ secrets.HWYUM_DOCKER_PASSWORD }}
  ALIYUM_DOCKER_USERNAME: ${{ secrets.ALIYUM_DOCKER_USERNAME }}
  ALIYUM_DOCKER_PASSWORD: ${{ secrets.ALIYUM_DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        run: |
          VERSION=$(cat VERSION)
          echo "RELEASE_VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Setting up the Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run python test
        run: |
          python manage.py test
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
      
      - name: Login to Huawei Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_HUAWEI }}
          username: ${{ env.HWYUM_DOCKER_USERNAME }}
          password: ${{ env.HWYUM_DOCKER_PASSWORD }}

      - name: build images
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
      
      - name: sync images to Huawei Cloud Container registry
        run: |
          chmod +x ./bin/skopeo
          ./bin/skopeo copy --all docker://docker.io/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }} docker://${{ env.DOCKER_REGISTRY_HUAWEI }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          ./bin/skopeo copy --all docker://docker.io/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:latest docker://${{ env.DOCKER_REGISTRY_HUAWEI }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        run: |
          VERSION=$(cat VERSION)
          echo "RELEASE_VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Create a compressed archive of the project
        run: |
          tar -czf release.tar.gz *
          mkdir -p release
          mv release.tar.gz release/

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-archive
          path: release/release.tar.gz

      - name: Extract release notes from CHANGELOG.md
        run: |
          VERSION=${RELEASE_VERSION#v}
          # 提取对应版本的发布说明
          RELEASE_NOTES=$(awk '/## \['"$VERSION"'\]/ {flag=1; next} /## \[/ {flag=0} flag' CHANGELOG.md)
          # 格式化发布说明
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "- **新版本发布**: $RELEASE_VERSION" >> $GITHUB_ENV
          echo "- **更新内容**:" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
          files: release/release.tar.gz
