name: Docker Image CI

on:
  push:
    tags:
      - 'v1.[1-9]+.[0-9]+*'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 设置Python版本
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6' 

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 运行测试
        run: |
          python manage.py test
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: 登录dockerhub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN}}
      
      - name: 构建镜像
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            llody/udocker:latest
            llody/udocker:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Create a compressed archive of the project
          run: |
            tar -czf release.tar.gz *
            mkdir -p release
            mv release.tar.gz release/

        - name: Upload release artifact
          uses: actions/upload-artifact@v2
          with:
            name: release-archive
            path: release/release.tar.gz

        - name: Create a GitHub release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            release_name: Release ${{ github.ref_name }}
            body: |
              Release of version ${{ github.ref_name }}.
            draft: false
            prerelease: false
            files: release/release.tar.gz
        
      

      

